name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt@1.11'

      - name: Build with Maven
        run: mvn clean package

      - name: Generate profile_markdown.iml
        run: mvn idea:idea

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
